package com.yb.magicplayer.db.greendao.base;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yb.magicplayer.entity.LikeMusic;
import com.yb.magicplayer.entity.Music;
import com.yb.magicplayer.entity.PlayingQuene;
import com.yb.magicplayer.entity.PlayList;
import com.yb.magicplayer.entity.RecentPlay;

import com.yb.magicplayer.db.greendao.base.LikeMusicDao;
import com.yb.magicplayer.db.greendao.base.MusicDao;
import com.yb.magicplayer.db.greendao.base.PlayingQueneDao;
import com.yb.magicplayer.db.greendao.base.PlayListDao;
import com.yb.magicplayer.db.greendao.base.RecentPlayDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig likeMusicDaoConfig;
    private final DaoConfig musicDaoConfig;
    private final DaoConfig playingQueneDaoConfig;
    private final DaoConfig playListDaoConfig;
    private final DaoConfig recentPlayDaoConfig;

    private final LikeMusicDao likeMusicDao;
    private final MusicDao musicDao;
    private final PlayingQueneDao playingQueneDao;
    private final PlayListDao playListDao;
    private final RecentPlayDao recentPlayDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        likeMusicDaoConfig = daoConfigMap.get(LikeMusicDao.class).clone();
        likeMusicDaoConfig.initIdentityScope(type);

        musicDaoConfig = daoConfigMap.get(MusicDao.class).clone();
        musicDaoConfig.initIdentityScope(type);

        playingQueneDaoConfig = daoConfigMap.get(PlayingQueneDao.class).clone();
        playingQueneDaoConfig.initIdentityScope(type);

        playListDaoConfig = daoConfigMap.get(PlayListDao.class).clone();
        playListDaoConfig.initIdentityScope(type);

        recentPlayDaoConfig = daoConfigMap.get(RecentPlayDao.class).clone();
        recentPlayDaoConfig.initIdentityScope(type);

        likeMusicDao = new LikeMusicDao(likeMusicDaoConfig, this);
        musicDao = new MusicDao(musicDaoConfig, this);
        playingQueneDao = new PlayingQueneDao(playingQueneDaoConfig, this);
        playListDao = new PlayListDao(playListDaoConfig, this);
        recentPlayDao = new RecentPlayDao(recentPlayDaoConfig, this);

        registerDao(LikeMusic.class, likeMusicDao);
        registerDao(Music.class, musicDao);
        registerDao(PlayingQuene.class, playingQueneDao);
        registerDao(PlayList.class, playListDao);
        registerDao(RecentPlay.class, recentPlayDao);
    }
    
    public void clear() {
        likeMusicDaoConfig.clearIdentityScope();
        musicDaoConfig.clearIdentityScope();
        playingQueneDaoConfig.clearIdentityScope();
        playListDaoConfig.clearIdentityScope();
        recentPlayDaoConfig.clearIdentityScope();
    }

    public LikeMusicDao getLikeMusicDao() {
        return likeMusicDao;
    }

    public MusicDao getMusicDao() {
        return musicDao;
    }

    public PlayingQueneDao getPlayingQueneDao() {
        return playingQueneDao;
    }

    public PlayListDao getPlayListDao() {
        return playListDao;
    }

    public RecentPlayDao getRecentPlayDao() {
        return recentPlayDao;
    }

}
