package com.yb.magicplayer.db.greendao.base;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yb.magicplayer.entity.Music;

import com.yb.magicplayer.entity.RecentPlay;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RECENT_PLAY".
*/
public class RecentPlayDao extends AbstractDao<RecentPlay, Long> {

    public static final String TABLENAME = "RECENT_PLAY";

    /**
     * Properties of entity RecentPlay.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property MusicId = new Property(1, long.class, "musicId", false, "MUSIC_ID");
        public final static Property PlayTime = new Property(2, java.util.Date.class, "playTime", false, "PLAY_TIME");
        public final static Property Music = new Property(3, Long.class, "music", false, "MUSIC");
    }

    private DaoSession daoSession;


    public RecentPlayDao(DaoConfig config) {
        super(config);
    }
    
    public RecentPlayDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RECENT_PLAY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"MUSIC_ID\" INTEGER NOT NULL ," + // 1: musicId
                "\"PLAY_TIME\" INTEGER," + // 2: playTime
                "\"MUSIC\" INTEGER);"); // 3: music
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RECENT_PLAY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RecentPlay entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getMusicId());
 
        java.util.Date playTime = entity.getPlayTime();
        if (playTime != null) {
            stmt.bindLong(3, playTime.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RecentPlay entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getMusicId());
 
        java.util.Date playTime = entity.getPlayTime();
        if (playTime != null) {
            stmt.bindLong(3, playTime.getTime());
        }
    }

    @Override
    protected final void attachEntity(RecentPlay entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public RecentPlay readEntity(Cursor cursor, int offset) {
        RecentPlay entity = new RecentPlay( //
            cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // musicId
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)) // playTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RecentPlay entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setMusicId(cursor.getLong(offset + 1));
        entity.setPlayTime(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(RecentPlay entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(RecentPlay entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(RecentPlay entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getMusicDao().getAllColumns());
            builder.append(" FROM RECENT_PLAY T");
            builder.append(" LEFT JOIN MUSIC T0 ON T.\"MUSIC\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected RecentPlay loadCurrentDeep(Cursor cursor, boolean lock) {
        RecentPlay entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Music music = loadCurrentOther(daoSession.getMusicDao(), cursor, offset);
        entity.setMusic(music);

        return entity;    
    }

    public RecentPlay loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<RecentPlay> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<RecentPlay> list = new ArrayList<RecentPlay>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<RecentPlay> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<RecentPlay> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
